### ISSUE TITLE
selector for `current` element in CollectionBinder

### ISSUE THREAD

**Issue by fcamblor** [theironcook/Backbone.ModelBinder#179]
I have a `Backbone.Collection` generating 1 `<li>` tag per `Backbone.Model`

I'd like to bind some the attribute `foo` of my current `Backbone.Model` on the `li`'s `class` attribute.

Problem is : I don't know how to tell `Backbone.ModelBinder` to apply it on selector `this`.

Some code snippet :
```
this.myCollection = new Backbone.Collection();
var myBinder = new Backbone.CollectionBinder(
    new Backbone.CollectionBinder.ElManagerFactory(
        jqOuterHtml(dayHtml),
        {
            // 'li' selector doesn't work here... because it will search for "sub-li" elements
            foo: { selector: 'li', elAttribute: 'class' }
        }
    )
);

myBinder.bind(this.$el, this.myCollection);
```

**Comment by platinumazure** [comment]
Hi @fcamblor, I can't speak for the active maintainers (if there are any!) but I think this is great to add to the docs, so I will do so in a pull request.

Incidentally, this is also true for Backbone View event declarations as well, although in that case you at least have the event name on the same line:

    var MyView = Backbone.View.extend({
        events: {
            "click li": "onSubLiClicked",
            "click": "onMeClicked"
        }
    });

In the above example, the second line is listening for click events on the root view element itself (`this.$el`).

**Comment by fcamblor** [comment]
Fine, thanks for the precision on `Backbone.View`

**Comment by platinumazure** [comment]
@fcamblor @theironcook Since the docs have been updated in master, would you like to close this issue?

**Comment by theironcook** [comment]
Yup, closing now.  Thanks for the reminder @platinumazure

**Comment by fcamblor** [comment]
good for me thx :)

Frédéric Camblor  <http://fcamblor.wordpress.com/>
<http://www.twitter.com/fcamblor>
BDX.io <http://bdx.io> & Bordeaux JUG <http://bordeauxjug.org/> Leader
Restx <http://restx.io/> commiter
Jenkins <http://jenkins-ci.org/> community member & plugin commiter
