### ISSUE TITLE
undelegate vs changeTriggers

### ISSUE THREAD

**Issue by mullerzs** [theironcook/Backbone.ModelBinder#187]
This bug came back:
* Fixed the default jQuery selector for all elements to be '*' instead of ''. The undelegate events no longer works in jQuery 1.8.3 with the ''

I suggest using .on / .off instead of .delegate / .undelegate, as the latter methods became obsolete, and the empty selector works well with .on /.off, so no need to use '*'.

**Comment by platinumazure** [comment]
@mullerzs Can you try with the version of code in my pull request and let me know if this is fixed?

**Comment by mullerzs** [comment]
Yes, this fixes the problem.

**Comment by theironcook** [comment]
@platinumazure @mullerzs 
Sorry but can someone just tell me what pull requests to accept now.  I don't have a ton of time to go through and verify all of the fixes so I'll just have to trust you guys to tell me what will work...

**Comment by platinumazure** [comment]
@theironcook Pull request #205 should fix #187 and #193 and should be safe to merge. Please let me know if you see any problems with that pull request. Thanks!

**Comment by platinumazure** [comment]
@theironcook Thanks for merging the PR.

@theironcook @mullerzs I think this issue can be closed too-- agree?

**Comment by theironcook** [comment]
Yup.  Thanks, this was a pretty serious issue to fix.
