### ISSUE TITLE
Problem with undelegate

### ISSUE THREAD

**Issue by qchroman** [theironcook/Backbone.ModelBinder#193]
Hello,

I think I may have found an issue when was playing with converters. I have added a converter to one of the bindings and noticed that it is called 3 times. I have checked my code and I do call bind() 3 times. Per the source code and the documentation the unbind() should be called internally, so I started digging. The unbind() is called indeed, but the problem is that the following line didn't remove event handlers from the HTML element:

```javascript
$(this._rootEl).undelegate(selector, event, this._onElChanged);
```

Changing it to

```javascript
$(this._rootEl).off(event, selector, this._onElChanged);
```

and changing how event handlers are attached to the element's event in _bindViewToModel_ from _delegate_ to _on_

```javascript
$(this._rootEl).on(event, selector, this._onElChanged);
```

solved the problem.

**Comment by platinumazure** [comment]
@qchroman @chuyler1 Can you try with the version of code in my pull request and let me know if this is fixed?
