### ISSUE TITLE
main in package.json should be a string

### ISSUE THREAD

**Issue by shuvalov-anton** [theironcook/Backbone.ModelBinder#195]
[Link to npm docs][1]. Just replace [array in `main` field][2] to string. Without this fix your module are unusable with browserify. 

[1]: https://www.npmjs.org/doc/files/package.json.html#main
[2]: https://github.com/theironcook/Backbone.ModelBinder/blob/master/package.json#L13

**Comment by platinumazure** [comment]
@shuvalov-anton I've opened a pull request; please take a look and let me know if anything else needs to be done. Thanks!
