### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by SimenB** [theironcook/Backbone.ModelBinder#215]
Please :pray: 
All the cool kids publish their modules to npm these days :smile: 

Also, please merge #204

**Comment by theironcook** [comment]
@SimenB  you make a very compelling argument.  Sure, I've merged #204.  I'm sorry but I'm pretty busy these days.  How does the lazy man push the module to npm these days?

**Comment by SimenB** [comment]
It was a very well-formed request, I know.

Well, you'd have to cleanup the package.json somewhat (as npm only supports lower-case named modules). I went a bit further though, and made a PR (#216) if you'd rather merge.

Then just follow https://docs.npmjs.com/getting-started/publishing-npm-packages

Gist is install `node`, run `npm adduser` then `npm publish`

**Comment by maticko** [comment]
:+1:

**Comment by theironcook** [comment]
https://www.npmjs.com/package/backbone.modelbinder

Done, sorry it's taken me so long.

**Comment by SimenB** [comment]
@theironcook Awesome, thanks! Another lib I can delete from my source tree :smile:
