### ISSUE TITLE
Can we cut release v1.0.7 (or v1.1.0)?

### ISSUE THREAD

**Issue by platinumazure** [theironcook/Backbone.ModelBinder#217]
We have a decent amount of [new functionality][1] in master since the last release (v1.0.6). Any chance of cutting a release?

* Fixed `createEl` code not to require that `Backbone.View#render` returns `this`
* Don't sort elements on `add` event (only do so on sort)
* Fixed package.json to make NPM publishing possible (fixes #195)
* Use jQuery `.on` instead of `.delegate` for event binding (to move off of deprecated `.delegate` function)
* Use `.prop("checked")` instead of `.attr("checked")` (fixes #199)
* Fixed autoSort behavior to actually work when the collection changes

If this doesn't seem like enough new functionality, perhaps it might be worth merging #216 (which dovetails nicely with #195) and have this be the first version published to NPM?

  [1]: https://github.com/theironcook/Backbone.ModelBinder/compare/v1.0.6...master

**Comment by theironcook** [comment]
Done.  Thank you for the awesome summary of what's changed!
